# Generated by Django 4.2.9 on 2024-02-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
    ]
