# Generated by Django 4.2.9 on 2024-02-04 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_category_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="price",
        ),
    ]
