# Generated by Django 4.2.9 on 2024-02-04 13:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0005_versioncategory_version"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versioncategory",
            options={
                "verbose_name": "Версия каталога",
                "verbose_name_plural": "Версии каталога",
            },
        ),
    ]
